"""ajout tables reservation paiement billet

Revision ID: 0516e0e9dd8a
Revises: 46ec6125a47a
Create Date: 2026-09-07 15:01:25.402650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0516e0e9dd8a'
down_revision: Union[str, Sequence[str], None] = '46ec6125a47a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(), nullable=False),
    sa.Column('date_reservation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('evenement_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evenement_id'], ['evenements.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservations_id'), 'reservations', ['id'], unique=False)
    op.create_table('billets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_billet', sa.String(), nullable=False),
    sa.Column('qr_code', sa.String(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('date_emission', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_code'),
    sa.UniqueConstraint('reservation_id')
    )
    op.create_index(op.f('ix_billets_id'), 'billets', ['id'], unique=False)
    op.create_index(op.f('ix_billets_numero_billet'), 'billets', ['numero_billet'], unique=True)
    op.create_table('paiements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('statut_paiement', sa.String(), nullable=False),
    sa.Column('mode_paiement', sa.String(), nullable=False),
    sa.Column('date_paiement', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reservation_id')
    )
    op.create_index(op.f('ix_paiements_id'), 'paiements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paiements_id'), table_name='paiements')
    op.drop_table('paiements')
    op.drop_index(op.f('ix_billets_numero_billet'), table_name='billets')
    op.drop_index(op.f('ix_billets_id'), table_name='billets')
    op.drop_table('billets')
    op.drop_index(op.f('ix_reservations_id'), table_name='reservations')
    op.drop_table('reservations')
    # ### end Alembic commands ###
