"""ajout score_engagement_total sur recommandation

Revision ID: 1b3c97329177
Revises: 532484f093bb
Create Date: 2026-09-15 12:08:02.437702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b3c97329177'
down_revision: Union[str, Sequence[str], None] = '532484f093bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommandations', sa.Column('score_engagement_total', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommandations', 'score_engagement_total')
    # ### end Alembic commands ###
