"""ajout tables interactions et recommandations

Revision ID: 46ec6125a47a
Revises: 
Create Date: 2026-09-04 14:47:22.553066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46ec6125a47a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artistes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('genre_artistique', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artistes_id'), 'artistes', ['id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('lieux',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('adresse', sa.String(), nullable=True),
    sa.Column('ville', sa.String(), nullable=True),
    sa.Column('capacite', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lieux_id'), 'lieux', ['id'], unique=False)
    op.create_table('evenements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('date_debut', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('capacite', sa.Integer(), nullable=True),
    sa.Column('prix_billet', sa.Float(), nullable=True),
    sa.Column('statut_validation', sa.String(), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('lieu_id', sa.Integer(), nullable=True),
    sa.Column('categorie_id', sa.Integer(), nullable=True),
    sa.Column('organisateur_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categorie_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['lieu_id'], ['lieux.id'], ),
    sa.ForeignKeyConstraint(['organisateur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evenements_id'), 'evenements', ['id'], unique=False)
    op.create_index(op.f('ix_evenements_titre'), 'evenements', ['titre'], unique=False)
    op.create_table('propositions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('ARTISTE', 'LIEU', 'CATEGORIE', name='propositiontype'), nullable=False),
    sa.Column('libelle', sa.String(), nullable=False),
    sa.Column('date_proposition', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('evenement_id', sa.Integer(), nullable=False),
    sa.Column('artiste_id', sa.Integer(), nullable=True),
    sa.Column('lieu_id', sa.Integer(), nullable=True),
    sa.Column('categorie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artiste_id'], ['artistes.id'], ),
    sa.ForeignKeyConstraint(['categorie_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['evenement_id'], ['evenements.id'], ),
    sa.ForeignKeyConstraint(['lieu_id'], ['lieux.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_propositions_id'), 'propositions', ['id'], unique=False)
    op.create_table('recommandations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('niveau_interet_estime', sa.Float(), nullable=True),
    sa.Column('participation_estimee', sa.Integer(), nullable=True),
    sa.Column('date_calcul', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('evenement_id', sa.Integer(), nullable=False),
    sa.Column('artiste_id', sa.Integer(), nullable=True),
    sa.Column('lieu_id', sa.Integer(), nullable=True),
    sa.Column('categorie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artiste_id'], ['artistes.id'], ),
    sa.ForeignKeyConstraint(['categorie_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['evenement_id'], ['evenements.id'], ),
    sa.ForeignKeyConstraint(['lieu_id'], ['lieux.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evenement_id')
    )
    op.create_index(op.f('ix_recommandations_id'), 'recommandations', ['id'], unique=False)
    op.create_table('interactions_publiques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_interaction', sa.Enum('LIKE', 'COMMENTAIRE', 'FAVORI', name='interactiontype'), nullable=False),
    sa.Column('contenu', sa.String(), nullable=True),
    sa.Column('date_interaction', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('proposition_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['proposition_id'], ['propositions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_publiques_id'), 'interactions_publiques', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interactions_publiques_id'), table_name='interactions_publiques')
    op.drop_table('interactions_publiques')
    op.drop_index(op.f('ix_recommandations_id'), table_name='recommandations')
    op.drop_table('recommandations')
    op.drop_index(op.f('ix_propositions_id'), table_name='propositions')
    op.drop_table('propositions')
    op.drop_index(op.f('ix_evenements_titre'), table_name='evenements')
    op.drop_index(op.f('ix_evenements_id'), table_name='evenements')
    op.drop_table('evenements')
    op.drop_index(op.f('ix_lieux_id'), table_name='lieux')
    op.drop_table('lieux')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_artistes_id'), table_name='artistes')
    op.drop_table('artistes')
    # ### end Alembic commands ###
