"""ajout reactions waouh j'adore et participant_id nullable

Revision ID: 532484f093bb
Revises: 5da13305488d
Create Date: 2026-09-15 09:12:27.787924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '532484f093bb'
down_revision: Union[str, Sequence[str], None] = '5da13305488d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE interactiontype ADD VALUE IF NOT EXISTS 'WAOUH'")
    op.execute("ALTER TYPE interactiontype ADD VALUE IF NOT EXISTS 'JADORE'")
    op.alter_column('interactions_publiques', 'participant_id',
               existing_type=sa.INTEGER(),
               nullable=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interactions_publiques', 'participant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
