"""correction fk participant_id vers participants

Revision ID: 5da13305488d
Revises: bea5b264c81d
Create Date: 2026-09-12 22:55:36.889297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5da13305488d'
down_revision: Union[str, Sequence[str], None] = 'bea5b264c81d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('interactions_publiques_participant_id_fkey'), 'interactions_publiques', type_='foreignkey')
    op.create_foreign_key(None, 'interactions_publiques', 'participants', ['participant_id'], ['id'])
    op.drop_constraint(op.f('reservations_participant_id_fkey'), 'reservations', type_='foreignkey')
    op.create_foreign_key(None, 'reservations', 'participants', ['participant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.create_foreign_key(op.f('reservations_participant_id_fkey'), 'reservations', 'users', ['participant_id'], ['id'])
    op.drop_constraint(None, 'interactions_publiques', type_='foreignkey')
    op.create_foreign_key(op.f('interactions_publiques_participant_id_fkey'), 'interactions_publiques', 'users', ['participant_id'], ['id'])
    # ### end Alembic commands ###
